server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push
  - url: http://loki-svc.34.80.150.150.nip.io/loki/api/v1/push

scrape_configs:
- job_name: VM-1
  static_configs:
  - targets:
      - localhost
    labels:
      job: VM-1
      __path__: /var/log/*log
      host: grafana
