objstoreConfig: |-
  type: GCS
  config:
    bucket: "thanos-monitoring"
    service_account: |-
      {
        "type": "service_account",
        "project_id": "klusternetes-prod",
        "private_key_id": "36c63e1293dummyffefec2",
        "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANB-dummy-dummyfM/aUIwZpDEcKCgP/\n-----END PRIVATE KEY-----\n",
        "client_email": "monitoring-demo-sa@dummy.iam.gserviceaccount.com",
        "client_id": "108292562321727295768",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/monitoring-demo-sa%40klusternetes-prod.iam.gserviceaccount.com"
      }
receive:
  enabled: true
  ingress:
    enabled: true
    hostname: thanos-receive.6jxlxp1tuuo9z4crirpd.apps.eu-hlski.klusternetes.com